openapi: 3.0.0
info:
  title: "Api d'échange"
  version: '1.0'
  description: |-
    Api permettant l'échange d'un dossier d'une commande oui.sncf.
    Elle permet:
    * la recherche de nouvelles solutions,
    * la gestion de la balance,
    * le paiement du complément en cas de balance positive,
    * le remboursement en cas de balance négative.
servers:
  - url: 'http://localhost:3000'
paths:
  '/orders/{id}/{folderReference}/exchange':
    parameters:
      - type: string
        name: id
        in: path
        required: true
        description: identifiant de la commande oui.sncf
        schema:
          type: string
      - type: string
        name: folderReference
        in: path
        required: true
        description: identifiant du dossier dans la commande oui.sncf
        schema:
          type: string
    post:
      summary: "Créer un nouveau processus d'échange"
      responses:
        '200':
          description: OK
      description: "Utiliser ce endpoint pour créer un nouveau processus d'échange concernant le dossier indiqué dans la commande oui.sncf."
components:
  schemas: {}
