openapi: 3.0.0
info:
  title: "Api d'échange"
  version: '1.0'
  description: |-
    Api permettant l'échange d'un dossier d'une commande oui.sncf.
    Elle permet:
    * la recherche de nouvelles solutions,
    * la gestion de la balance,
    * le paiement du complément en cas de balance positive,
    * le remboursement en cas de balance négative.
servers:
  - url: 'http://localhost:3000'
paths:
  /exchanges:
    parameters: []
    post:
      summary: "Créer un nouveau processus d'échange"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/exchange.v1.yaml
        '':
          content:
            application/json:
              schema:
                $ref: ./models/exchange.v1.yaml
      description: "Utiliser ce endpoint pour créer un nouveau processus d'échange concernant le dossier indiqué dans la commande oui.sncf."
      tags:
        - exchange
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                orderId:
                  type: string
                  description: Order ID Oui.sncf
                folderReferenceToExchange:
                  type: string
                  description: Référence du dossier à échanger.
            examples: {}
        description: ''
  '/exchanges/{id}':
    parameters:
      - type: string
        name: id
        in: path
        required: true
        description: "identifiant du processus d'échange"
        schema:
          type: string
    get:
      summary: "Récupérer l'état actuel du processus d'échange"
      tags:
        - exchange
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/exchange.v1.yaml
  '/exchanges/{id}/wishes/':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    post:
      summary: "Envoi les souhaits d'échange"
      responses:
        '200':
          description: OK
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/Wishes/wish.v1.yaml
            examples:
              example-1: {}
      tags:
        - exchange
components:
  schemas: {}
